version: '3.0'
services:
  busybox:
    image: registry.access.redhat.com/ubi8/ubi@sha256:27e79c4c0b76e92bdbbefd7fce5fa54c88957183f4228ccd9afc0beeca40fcde
    command: |
      curl -v -X "PUT" "${S3_URL}" -H "Authorization: ${AUTHORIZATION}"  -H "Content-Type: text/plain"  -d @/var/hyperprotect/se-checksums.txt.enc
    volumes:
      - /var/hyperprotect/:/var/hyperprotect/:ro
    environment:
      - AUTHORIZATION
      - S3_URL
