version: '3.0'
services:
  busybox:
    image: registry.access.redhat.com/ubi8/ubi@sha256:19eae3d00adb37538a62b9bd093fd1e01dc6197f1925e960224244a1ed52bfb5
    command: |
      curl -v -X "PUT" "${S3_URL}" -H "Authorization: ${AUTHORIZATION}"  -H "Content-Type: text/plain"  -d @/var/hyperprotect/se-checksums.txt.enc
    volumes:
      - /var/hyperprotect/:/var/hyperprotect/:ro
    environment:
      - AUTHORIZATION
      - S3_URL
