version: '3.0'
services:
  busybox:
    image: registry.access.redhat.com/ubi8/ubi@sha256:79d46e7029c2b13a713b2089650fd235aadb3e6e449c79f6741d6c9381ab41a1
    command: |
      curl -v -X "PUT" "${S3_URL}" -H "Authorization: ${AUTHORIZATION}"  -H "Content-Type: text/plain"  -d @/var/hyperprotect/se-checksums.txt.enc
    volumes:
      - /var/hyperprotect/:/var/hyperprotect/:ro
    environment:
      - AUTHORIZATION
      - S3_URL
