apiVersion: v1
kind: Pod
metadata:
  name: postgresdb
spec:
  containers:
  - name: postgres
    image: docker.io/library/postgres:12@sha256:429c57f9ae8f379601df6df7448b0c2c8df4da23d7ba2cb57fee8da8f262eda0
    env:
      - name: POSTGRES_HOST_AUTH_METHOD
        valueFrom:
          configMapKeyRef:
            name: env-user
            key: POSTGRES_HOST_AUTH_METHOD
      - name: POSTGRES_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: env-user
            key: POSTGRES_PASSWORD
    ports:
      - containerPort: 5432
        hostPort: 5432
    restartpolicy: Always