apiVersion: v1
kind: Pod
metadata:
  name: nginxdemos
spec:
  containers:
  - name: nginxdemos
    image: docker.io/nginxdemos/hello@sha256:dedfbe85183df66f3fdc99accf53e1b2171908dffd4d6556603ba4810b1fce6e
    ports:
    - containerPort: 80
      hostPort: 80
  restartpolicy: Always