services:
  logging:
    image: docker.io/library/ubuntu@sha256:6064e6a1e8c281e943e6d14d4722643ee9fa828d17764db84863811950ffb9ef
    volumes:
      - ./key.pub:/var/logging/logging.pub:ro
      - ./bin/:/var/logging/bin/:ro
    command: bash /var/logging/bin/example.sh