services:
  logging:
    image: docker.io/library/ubuntu@sha256:440dcf6a5640b2ae5c77724e68787a906afb8ddee98bf86db94eea8528c2c076
    volumes:
      - ./key.pub:/var/logging/logging.pub:ro
      - ./bin/:/var/logging/bin/:ro
    command: bash /var/logging/bin/example.sh