services:
  logging:
    image: docker.io/library/ubuntu@sha256:b59d21599a2b151e23eea5f6602f4af4d7d31c4e236d22bf0b62b86d2e386b8f
    volumes:
      - ./key.pub:/var/logging/logging.pub:ro
      - ./bin/:/var/logging/bin/:ro
    command: bash /var/logging/bin/example.sh