services:
  postgresql:
    image: docker.io/library/postgres:12@sha256:7206ad3a83977749e09f9ac1e7ef41f70b2652fdcbce73994eeaf446b9da327b
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust